name: Build and Push Docker Images

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'
      - 'backend/**'
  pull_request:
    branches:
      - main
    paths:
      - 'frontend/**'
      - 'backend/**'

jobs:
  # Define the build job
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4


      - name: Login to Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin

      # Step 4: Build and push the frontend Docker image if there are changes in the frontend directory
      - name: Build and Push Frontend Image
        run: |
          if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '^frontend/' > /dev/null; then
            echo "Changes detected in frontend, building and pushing Docker image."
            cd ./frontend
            docker build -t ${{ secrets.DOCKER_USERNAME }}/frontend:latest ./frontend
            docker push ${{ secrets.DOCKER_USERNAME }}/frontend:latest
          else
            echo "No changes in frontend directory, skipping."
          fi

      # Step 5: Build and push the backend Docker image if there are changes in the backend directory
      - name: Build and Push Backend Image
        run: |
          if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '^backend/' > /dev/null; then
            echo "Changes detected in backend, building and pushing Docker image."
            cd ./backend
            docker build -t ${{ secrets.DOCKER_USERNAME }}/backend:latest ./backend
            docker push ${{ secrets.DOCKER_USERNAME }}/backend:latest
          else
            echo "No changes in backend directory, skipping."
          fi
